config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  # get '/users', to: 'users#index'
  resources :home
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @messages = Message.page(params[:page]).per(5)
        # @messages = Message.all
    end

    def new
        @message = Message.new
    end

    def create

        @message = Message.new(message_params)
    
        # flash[:notice] = "event was successfully created"
        if @message.save
            redirect_to home_index_path, notice: 'Message was successfully created.'
        else
            render :action => :new
        end
    end

    def edit
        @message = Message.find(params[:id])
    end

    def update
        @message = Message.find(params[:id])
        @message.update(message_params)

        redirect_to home_index_path, notice: 'Message was successfully updated.'
    end

    def destroy
        @message = Message.find(params[:id])
        @message.destroy
      
        redirect_to home_index_path
    end

    private
  
    def message_params
        puts('---------')
        puts(params)
        puts('---------')
        params.require(:message).permit(:name, :message, :user_id)
        
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        # @messages = Message.page(params[:page]).per(5)
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/edit.html.erb
<h1>Edit Message</h1>

<%= form_for @message, :url => home_path do |f| %>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %><br />

    <%= f.label :message, "Message" %><br />
    <%= f.text_area :message %><br />

    <%= f.submit "Update" %>
<% end %>
<br />
<%= link_to 'Home', home_index_path %>

app/views/home/index.html.erb
<style>
    ul,li{
        list-style: none;
        padding: 0;
    }
    li{
        padding: .5em 1em;
        margin: .5em
        background-color: rgb(209, 209, 209);
    }
    ul{
        width: 50vw;
        background-color: rgb(233, 233, 233);
        margin: 1em auto;
        display: flex;
        justify-content: center;
    }

    .size{
        font-size: 20px;
    }
</style>


<h1>Message Board</h1>

<% if user_signed_in? %>
    -----------------------------------------------</br>
    Welcome, <%= current_user.name %></br>
    
    <% if current_user.admin? %>
        <p>you are system administrator</p>
        There are <%= User.count %> users in the system.</br>
        
        <%= link_to "User list", :controller => 'users', :action => 'index' %></br>

    <% end %>
    <%= link_to "Account Settings", edit_user_registration_path %></br>
    <%= link_to "log out", destroy_user_session_path, 'data-turbo-method': :delete %></br>
    -----------------------------------------------

<% else %>
    <%= link_to "Sign up", new_user_registration_path %></br>
    <%= link_to "Sign in", new_user_session_path %>
<% end %>

<lu>
    <%= paginate @messages %>
    <% @messages.each do |message| %>
        <li class="size">
            <%= message.name %>
            :
            <%= message.message %> 
            <% if user_signed_in? %>
                <% if current_user.admin? || current_user.id == message.user_id%>
                    <%= link_to 'Edit', edit_home_path(message) %>
                    <%= link_to 'Delete', home_path(message), 'data-turbo-method': :delete %>
                <% end %>
            <% end %>
        </li>
        
    <% end %>
</lu>
<% if user_signed_in? %>
    <%= link_to 'New Message', new_home_path %>
<% end %>

app/views/home/new.html.erb
<h1>New Message</h1>


<%= form_for @message, :url => home_index_path do |f| %>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %><br />
    <%= f.label :message, "Message" %><br />
    <%= f.text_area :message %><br />
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Create" %>
<% end %>
<br />
<p>you are <%= current_user.id %>
<%= link_to 'Home', home_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>"Message Board"</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<style>
    ul,li{
        list-style: none;
        padding: 0;
    }
    li{
        padding: .5em 1em;
        margin: .5em
        background-color: rgb(209, 209, 209);
    }
    ul{
        width: 50vw;
        background-color: rgb(233, 233, 233);
        margin: 1em auto;
        display: flex;
        justify-content: center;
    }

    .size{
        font-size: 20px;
    }
</style>


<h1>All Users</h1>

<lu>
    <% @users.each do |user| %>
        <li class="size">
            <%= user.name %>
            :
            <%= user.email %> 
        </li>
        
    <% end %>
</lu>

<%= link_to "Home", :controller => 'home', :action => 'index' %></br>